extension_dir = "C:\Users\Gellért Szalai\AppData\Local\Microsoft\WinGet\Packages\PHP.PHP.8.5_Microsoft.Winget.Source_8wekyb3d8bbwe\ext"
extension=openssl
extension=mbstring
extension=pdo_mysql
extension=fileinfo
extension=curl
extension=zip
memory_limit=512M